<?php
// Generated by Zend Framework 2
return array(
    'UthandoMail\Module'                                     => __DIR__ . '/Module.php',
    'UthandoMailQueue\Controller\MailQueueConsoleController' => __DIR__ . '/src/UthandoMailQueue/Controller/MailQueueConsoleController.php',
    'UthandoMail\Controller\MailQueueController'             => __DIR__ . '/src/UthandoMailQueue/Controller/MailQueueController.php',
    'UthandoMail\Hydrator\MailQueue'                         => __DIR__ . '/src/UthandoMailQueue/Hydrator/MailQueue.php',
    'UthandoMail\Mail\HtmlMessage'                           => __DIR__ . '/src/UthandoMailQueue/Mail/HtmlMessage.php',
    'UthandoMail\Mapper\MailQueue'                           => __DIR__ . '/src/UthandoMailQueue/Mapper/MailQueue.php',
    'UthandoMail\Model\MailQueue'                            => __DIR__ . '/src/UthandoMailQueue/Model/MailQueue.php',
    'UthandoMail\Service\MailQueue'                          => __DIR__ . '/src/UthandoMailQueue/Service/MailQueue.php',
);