<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoMail\Module'                                  => __DIR__ . '/Module.php',
    'UthandoMail\Controller\MailQueueConsoleController'   => __DIR__ . '/src/UthandoMail/Controller/MailQueueConsoleController.php',
    'UthandoMail\Controller\MailQueueController'          => __DIR__ . '/src/UthandoMail/Controller/MailQueueController.php',
    'UthandoMail\Event\MailListener'                      => __DIR__ . '/src/UthandoMail/Event/MailListener.php',
    'UthandoMail\Hydrator\MailQueue'                      => __DIR__ . '/src/UthandoMail/Hydrator/MailQueue.php',
    'UthandoMail\InputFilter\MailQueue'                   => __DIR__ . '/src/UthandoMail/InputFilter/MailQueue.php',
    'UthandoMail\Mapper\MailQueue'                        => __DIR__ . '/src/UthandoMail/Mapper/MailQueue.php',
    'UthandoMail\Model\Attachment'                        => __DIR__ . '/src/UthandoMail/Model/Attachment.php',
    'UthandoMail\Model\MailQueue'                         => __DIR__ . '/src/UthandoMail/Model/MailQueue.php',
    'UthandoMail\Options\MailOptions'                     => __DIR__ . '/src/UthandoMail/Options/MailOptions.php',
    'UthandoMail\Options\MailQueueOptions'                => __DIR__ . '/src/UthandoMail/Options/MailQueueOptions.php',
    'UthandoMail\Service\Factory\MailFactory'             => __DIR__ . '/src/UthandoMail/Service/Factory/MailFactory.php',
    'UthandoMail\Service\Factory\MailQueueOptionsFactory' => __DIR__ . '/src/UthandoMail/Service/Factory/MailQueueOptionsFactory.php',
    'UthandoMail\Service\Mail'                            => __DIR__ . '/src/UthandoMail/Service/Mail.php',
    'UthandoMail\Service\MailQueue'                       => __DIR__ . '/src/UthandoMail/Service/MailQueue.php',
);
