<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoMail\Module'                                => __DIR__ . '/Module.php',
    'UthandoMail\Controller\MailQueueConsoleController' => __DIR__ . '/src/UthandoMail/Controller/MailQueueConsoleController.php',
    'UthandoMail\Controller\MailQueueController'        => __DIR__ . '/src/UthandoMail/Controller/MailQueueController.php',
    'UthandoMail\Controller\SettingsController'         => __DIR__ . '/src/UthandoMail/Controller/SettingsController.php',
    'UthandoMail\Event\MailListener'                    => __DIR__ . '/src/UthandoMail/Event/MailListener.php',
    'UthandoMail\Form\Element\MailTransportList'        => __DIR__ . '/src/UthandoMail/Form/Element/MailTransportList.php',
    'UthandoMail\Hydrator\MailQueue'                    => __DIR__ . '/src/UthandoMail/Hydrator/MailQueue.php',
    'UthandoMail\InputFilter\MailQueue'                 => __DIR__ . '/src/UthandoMail/InputFilter/MailQueue.php',
    'UthandoMail\Mapper\MailQueue'                      => __DIR__ . '/src/UthandoMail/Mapper/MailQueue.php',
    'UthandoMail\Model\Attachment'                      => __DIR__ . '/src/UthandoMail/Model/Attachment.php',
    'UthandoMail\Model\MailQueue'                       => __DIR__ . '/src/UthandoMail/Model/MailQueue.php',
    'UthandoMail\Options\MailOptions'                   => __DIR__ . '/src/UthandoMail/Options/MailOptions.php',
    'UthandoMail\Service\Factory\MailFactory'           => __DIR__ . '/src/UthandoMail/Service/Factory/MailFactory.php',
    'UthandoMail\Service\Factory\MailOptionsFactory'    => __DIR__ . '/src/UthandoMail/Service/Factory/MailOptionsFactory.php',
    'UthandoMail\Service\Mail'                          => __DIR__ . '/src/UthandoMail/Service/Mail.php',
    'UthandoMail\Service\MailQueue'                     => __DIR__ . '/src/UthandoMail/Service/MailQueue.php',
    'UthandoMail\View\Helper\MailAddress'               => __DIR__ . '/src/UthandoMail/View/Helper/MailAddress.php',
    'UthandoMailTest\Bootstrap'                         => __DIR__ . '/test/Bootstrap.php',
    'UthandoMailTest\Framework\ApplicationTestCase'     => __DIR__ . '/test/UthandoMailTest/Framework/ApplicationTestCase.php',
    'UthandoMailTest\Framework\TestCase'                => __DIR__ . '/test/UthandoMailTest/Framework/TestCase.php',
);
