<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-mail/mail-queue/index' => __DIR__ . '/view/uthando-mail/mail-queue/index.phtml',
    'uthando-mail/mail-queue/list'  => __DIR__ . '/view/uthando-mail/mail-queue/list.phtml',
);
