
<?php $this->headTitle('Mail Queue') ?>
<?php $this->layout()->pageTitle = $this->translate('Mail Queue');?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('Mail Queue List');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'mail-queue',
            'searchInputs'	=> [
                $this->translate('Recipient')	=> 'reciptient',
            ],
        ]);?>
    </div>
    <div id="table-mail-queue" class="admin-table">
        <?=$this->partial('uthando-mail/mail-queue/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-mail-queue').dataGrid({
	    url : 'mail-queue/list',
	    query: { sort : 'mailQueueId' },
	    searchForm : $('#search-mail-queue'),
	    paging : 'links',
	    columnSort: true,
	});
});
<?php $this->inlineScript()->captureEnd(); ?> 
