
<?php if (count($this->models) > 0): ?>
    <div class="table-responsive">
        <form id="form-mail-queue" method="post" action="<?=$this->url('admin/mail-queue/edit', [
    'action' => 'delete'
]);?>">
            <table id="mail-queue-list" class="table table-hover table-bordered table-condensed sortable-table">
                <thead>
                <tr>
                    <th data-field="mailQueueId"><?=$this->translate('Mail Queue Id');?></th>
                    <th data-field="recipient"><?=$this->translate('Recipient');?></th>
                    <th data-field="sender"><?=$this->translate('Sender');?></th>
                    <th data-field="subject"><?=$this->translate('Subject');?></th>
                    <th data-field="dateCreated"><?=$this->translate('Date Created');?></th>
                    <th><?=$this->translate('mails to delete');?></th>
                </tr>
                </thead>

                <tbody>
                <?php /* @var $row \UthandoMail\Model\MailQueueModel */ ?>
                <?php foreach ($this->models as $row): ?>
                    <tr>
                        <td><?= $this->escapeHtml($row->getMailQueueId()); ?></td>
                        <td><?= $this->escapeHtml($this->uthandoMailAddress($row, 'recipient')); ?></td>
                        <td><?= $this->escapeHtml($this->uthandoMailAddress($row, 'sender')); ?></td>
                        <td><?= $this->escapeHtml($row->getSubject()); ?></td>
                        <td><?= $this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
                        <td><input type="checkbox" name="ids[]" value="<?=$row->getMailQueueId();?>"></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <!-- Modal -->
            <div class="modal fade" id="delete-mail-dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h3><?=$this->translate('Warning');?></h3>
                        </div>

                        <div class="modal-body">
                            <p><?=$this->translate('Are you sure you want to delete the mail list?');?></p>
                            <h4 class="text-danger"><?=$this->translate('This action cannot be undone');?></h4>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">
                                <?=$this->translate("No Don't Do It");?>
                            </button>
                            <button type="submit" name="submit" class="btn btn-danger" value="delete">
                                <?=$this->translate('Yes Delete It');?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <?= $this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/mail-queue/page']
    ); ?>

<?php else: ?>
    <h4><?=$this->translate('No emails are in the queue');?></h4>
<?php endif; ?>
