<?php $this->headTitle('Mail Queue') ?>

<?php if (count($this->models) > 0): ?>
<div class="panel panel-default">
    <table id="mailQueue-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="mailQueueId">Mail Queue Id</th>
    			<th data-field="recipient">To</th>
    			<th data-field="sender">From</th>
    			<th data-field="subject">Subject</th>
    			<th data-field="dateCreated">Date Created</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    	<?php /* @var $row \UthandoMail\Model\MailQueue */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getMailQueueId()); ?></td>
    			<td><?=$this->escapeHtml($row->getRecipient()); ?></td>
    			<td><?=$this->escapeHtml($row->getSender()); ?></td>
    			<td><?=$this->escapeHtml($row->getSubject()); ?></td>
    			<td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
    			<td>
                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                    	'pk'		=> 'mailQueueuId',
                    	'id'		=> $row->getMailQueueId(),
    		    		'tableName'	=> 'mailQueue',
                    	'route'		=> 'admin/mail-queue/edit',
                        'edit'      => false,
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/mail-queue/page']
); ?>

<?php else: ?>
<h4>No emails are in the queue</h4>
<?php endif; ?>
