
<?php if (count($this->models) > 0): ?>
    <div class="table-responsive">
        <table id="mail-queue-list" class="table table-hover table-bordered table-condensed sortable-table">
            <thead>
            <tr>
                <th data-field="mailQueueId"><?=$this->translate('Mail Queue Id');?></th>
                <th data-field="recipient"><?=$this->translate('Recipient');?></th>
                <th data-field="sender"><?=$this->translate('Sender');?></th>
                <th data-field="subject"><?=$this->translate('Subject');?></th>
                <th data-field="dateCreated"><?=$this->translate('Date Created');?></th>
                <th><?=$this->translate('Actions');?></th>
            </tr>
            </thead>

            <tbody>
            <?php /* @var $row \UthandoMail\Model\MailQueue */ ?>
            <?php foreach ($this->models as $row): ?>
                <tr>
                    <td><?= $this->escapeHtml($row->getMailQueueId()); ?></td>
                    <td><?= $this->escapeHtml($this->uthandoMailAddress($row, 'recipient')); ?></td>
                    <td><?= $this->escapeHtml($this->uthandoMailAddress($row, 'sender')); ?></td>
                    <td><?= $this->escapeHtml($row->getSubject()); ?></td>
                    <td><?= $this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
                    <td>
                        <?= $this->partial('uthando-admin/partial/edit-actions', [
                            'pk' => 'mailQueueuId',
                            'id' => $row->getMailQueueId(),
                            'tableName' => 'mail-queue',
                            'route' => 'admin/mail-queue/edit',
                            'edit' => false,
                        ]); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?= $this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/mail-queue/page']
    ); ?>

<?php else: ?>
    <h4><?=$this->translate('No emails are in the queue');?></h4>
<?php endif; ?>
